apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-server
    spec:
      containers:
      - image: hairinwind/springkub-config-server
        name: springkub-config-server
        resources: {}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config/springkub
      volumes:
        - name: config-volume
          configMap:
            name: configserver-configmap
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: config-server
  name: config-server
spec:
  ports:
  - name: 8888-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  type: NodePort
status:
  loadBalancer: {}
