# this file has to be yml file, properties file will create error "No converter found..."
users.name: John Terry
users.dateOfBirth: 1970-12-31
users.country: CN
users.titles: doctor, MR
users.addresses[0]: {"streetAddress":"123 kingsway", "city":"vancouver"}
users.addresses[1]: {"streetAddress":"345 smith rd", "city":"burnaby"}